{
 "title": "tado° Dashboard",
 "description": "Grafana Dashboard for Prometheus eko/tado-exporter that shows the temperature setting, current temperature, humidity and activity for all rooms. A detailed view is shown based on the selected room.\r\n\r\nUsing this exporter: https://github.com/eko/tado-exporter",
 "tags": [ "tado" ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "zone",
    "label": "Zones",
    "query": {
     "query": "tado_activity_heating_power_percentage"
    }
   },
   { "name": "temperatureScale", "label": "Temperature Scale", "query": { "query": "tado_sensor_temperature_value" } }
  ]
 },
 "panels": [
  {
   "title": "Zone $zone",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatur",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 10, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}"
      }
     ]
    },
    {
     "title": "Set Temperature",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tado_setting_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
       "legendFormat": "Set Temperature"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "bargauge",
     "gridPos": { "h": 2, "w": 9, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "degree" } },
     "targets": [
      {
       "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
       "legendFormat": "Max:"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 15, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
       "legendFormat": "Max:"
      }
     ]
    },
    {
     "title": "Heating Power",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 10, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "tado_activity_heating_power_percentage{zone=\"$zone\"}",
       "legendFormat": "Heating Power"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
       "legendFormat": "Avg:"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
       "legendFormat": "Avg:"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
       "legendFormat": "Min:"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
       "legendFormat": "Min:"
      }
     ]
    }
   ]
  },
  {
   "title": "Zone Details $zone",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature: $zone",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "tado_sensor_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
       "legendFormat": "Current Temperature"
      },
      {
       "expr": "tado_setting_temperature_value{zone=\"$zone\",unit=\"$temperatureScale\"}",
       "legendFormat": "Set Temperature"
      }
     ]
    },
    {
     "title": "Heatingpower: $zone",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "tado_activity_heating_power_percentage{zone=\"$zone\"}"
      }
     ]
    }
   ]
  },
  { "title": "All Zones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Open Windows",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tado_sensor_window_opened{type=\"HEATING\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heatingpower: All Zones",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "tado_activity_heating_power_percentage"
    }
   ]
  },
  {
   "title": "Heating Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tado_activity_heating_power_percentage"
    }
   ]
  },
  {
   "title": "Set Temp",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "tado_setting_temperature_value{unit=\"celsius\"}",
     "legendFormat": "Set Temperature"
    }
   ]
  },
  {
   "title": "Temperature: All Zones",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{unit=\"celsius\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{unit=\"celsius\"}"
    }
   ]
  },
  {
   "title": "Min:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{unit=\"$temperatureScale\"}",
     "legendFormat": "Min:"
    }
   ]
  },
  {
   "title": "Max:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{unit=\"$temperatureScale\"}",
     "legendFormat": "Max:"
    }
   ]
  },
  {
   "title": "Avg:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tado_sensor_temperature_value{unit=\"$temperatureScale\"}",
     "legendFormat": "Avg:"
    }
   ]
  },
  {
   "title": "Humidity: All Zones",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage"
    }
   ]
  },
  {
   "title": "Min:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
     "legendFormat": "Min:"
    }
   ]
  },
  {
   "title": "Max:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
     "legendFormat": "Max:"
    }
   ]
  },
  {
   "title": "Avg:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tado_sensor_humidity_percentage{zone=\"$zone\"}",
     "legendFormat": "Avg:"
    }
   ]
  }
 ]
}